### ISSUE TITLE
TypeError: missing a required argument: 'credentials'

### ISSUE THREAD

**Issue by afelbs0216** [AlessandroLollo/prefect-stitch#8]
Using the code as instructed, I get the TypeError: missing a required argument: 'credentials. See code below. 

from prefect import flow
from prefect_stitch.tasks import (
    start_replication_job
)

@flow
def run_s3_stitch_job():
    start_replication_job(
        access_token="xxx",
        source_id=xxx
    )

if __name__ == "__main__":
    run_s3_stitch_job()

**Comment by AlessandroLollo** [comment]
Hey @afelbs0216 👋 
The docs are actually wrong, will fix it.
In the meantime, try the following:
```
from pydantic import SecretStr
from prefect import flow
from prefect_stitch.credentials import StitchCredentials
from prefect_stitch.tasks import (
start_replication_job
)

@flow
def run_s3_stitch_job():
  credentials = StitchCredentials(access_token=SecretStr("xxx"))
  start_replication_job(
      credentials=credentials,
      source_id="xxx"
  )

if name == "main":
run_s3_stitch_job()
```
